# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
es:
  languageCode: es-mx
  contentDir: content/es
  title: Erick I. Navarro Delgado
  params:
    description: Site description in Chinese...
  menu:
    main:
        - name: Acerca de mí
          url: '#about'
          weight: 10
        - name: Experiencia
          url: '#experience'
          weight: 20
        - name: Logros
          url: '#accomplishments'
          weight: 30
        - name: Publicaciones
          url: '#publications'
          weight: 50
        - name: Blog
          url: '#posts'
          weight: 60
